server:
  port: 5000

spring:
  jackson:
    serialization:
      indent_output: true

notifications:
  enabled: true
  email:
    enabled: false
    silenceInterval: 5
  telegram:
    enabled: true

aws:
  dynamodb:
    region: eu-central-1
mongodb:
  host: localhost
  port: 20001
  user: realestate_admin

---
spring:
  profiles:
    active: default

notifications:
  enabled: true
  email:
    enabled: false
    silenceInterval: 5
  telegram:
    enabled: true

---
spring:
  profiles:
    active: dev

notifications:
  enabled: true
  email:
    enabled: false
    silenceInterval: 5
  telegram:
    enabled: false