server:
  port: 5000

spring:
  jackson:
    serialization:
      indent_output: true

notifications:
  enabled: true
  email:
    enabled: false
    silenceInterval: 5
  telegram:
    enabled: true

aws:
  dynamodb:
    region: eu-central-1
mongodb:
  host: localhost
  port: 20001
  user: realestate_admin

---
spring.profiles: prod

notifications:
  enabled: true
  email:
    enabled: false
    silenceInterval: 5
  telegram:
    enabled: true

spring:
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54030/realestate
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

logging:
  config: classpath:logback-dev.xml

---
spring.profiles: dev

notifications:
  enabled: true
  email:
    enabled: false
    silenceInterval: 5
  telegram:
    enabled: false
spring:
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54030/realestate
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

logging:
  config: classpath:logback-dev.xml